language: common-lisp

addons:
  postgresql: "9.1"

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Install the latest versions of the major dependencies
  - git clone https://github.com/fukamachi/sxql.git quicklisp/local-projects/sxql
  - git clone https://github.com/fukamachi/cl-dbi.git quicklisp/local-projects/cl-dbi
  # Update package repos
  - sudo apt-get update
  # Install SQLite
  - sudo apt-get install -y sqlite3

before_script:
  # Set up MySQL
  - mysql -uroot -e "CREATE USER mysql_user@localhost IDENTIFIED BY 'mysql_pass';"
  - mysql -uroot -e "CREATE DATABASE mysql_db;"
  - mysql -uroot -e "GRANT ALL PRIVILEGES ON mysql_db.* TO mysql_user@localhost identified by 'mysql_pass';"
  # Set up Postgres
  - createdb -U postgres postgres_db
  - psql -U postgres -c "CREATE USER postgres_user WITH PASSWORD 'postgres_pass'"
  - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE postgres_db TO postgres_user"

script:
  - cl -e '(ql:quickload :fiveam)'
       -e '(setf fiveam:*debug-on-error* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(ql:quickload :crane-test)'

notifications:
  email:
    - eudoxiahp@gmail.com
